CREATE SCHEMA pace;

CREATE TABLE pace.users ( 
	id                   integer  NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	username             varchar(100)   ,
	password        text   ,
	config          json,
	CONSTRAINT pk_users_id PRIMARY KEY ( id ),
	CONSTRAINT idx_users UNIQUE ( username )
 );